#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
mkdir -p $install_dir

#copy files from with_root_access folder to the install_dir
cp -a ../sources/with_root_access/. $install_dir

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

# Create a dedicated php-fpm config
ynh_config_add_phpfpm

# Create a dedicated nginx config
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
